apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: danielagomez-es-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
- ./deployment.sops.yaml
- ./environment.sops.yaml
- ./registry.sops.yaml
